#!/bin/sh
# © Copyright 2018 JSS & Hayer - http://www.jsshayer.hu

set -e

quit () {
    [ -e $tmpdir/.tplink-get-config-tempdir ] && rm -rf $tmpdir || true
    [ "$1" = "" ] && exit 0 || true
    echo "$1" >&2
    exit 1
}

usage () {
    cat <<USAGE
TP-Link device config downloader by JSS&Hayer

usage:   tplink-get-config <device type> <output file> <host> <user> <password>
example: tplink-get-config sg3424 /var/backup/switch.cfg 192.168.0.1 admin verysecret

Device types:
 sg3424    - TP-Link TL-SG3424P Gigabit POE switch, or similar

USAGE
}

if [ "$5" = "" ]; then
    usage
    exit 1
fi

device=$1
output=$2
host=$3
user=$4
password=$5

tmpdir=$(mktemp -d)
touch $tmpdir/.tplink-get-config-tempdir
oldpwd="$(pwd)"
cd $tmpdir

# TP-Link SG3424 or similar
do_sg3424 () {
    # Login
    curl -sS -X POST -d "username=$user&password=$password&logon=Login" http://$host/logon/LogonRpm.htm >response_login
    if ! head -n 10 response_login |grep -q $user; then
        quit "Login failed"
    fi

    # Fetch
    curl -sS http://$host/userRpm/Config.cfg >response_config
    if ! head -n 1 response_config |grep -qe '^\!'; then
        quit "Login success, but can't fetch the config"
    fi

    # Logout
    curl -sS http://$host/userRpm/Logout.html >response_logout

    # Write output
    cd "$oldpwd"
    cat $tmpdir/response_config >$output
    quit
}

case $device in
    sg3424)             do_sg3424                       ;;
    *)                  usage; quit 'Unknown device!'   ;;
esac

